version: "3.9"
services:
  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=qwerty
  server:
    build: ./
    depends_on:
      - database
    restart: always
    networks:
      - default
    ports:
    - "3001:3001"
volumes:
  data:
